# Generated by Django 3.2.7 on 2021-10-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('FAQ_model', '0002_auto_20211007_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='faq',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AddField(
            model_name='categoria',
            name='departamento',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='faq',
            name='departamento',
            field=models.ManyToManyField(related_name='grupo_departamento', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='categorias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_name', to='FAQ_model.categoria'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
