# Generated by Django 3.2.7 on 2021-11-01 18:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ_model', '0003_auto_20211020_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
